name: rss-to-twitter
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
    inputs:
      updateMinutes:
        description: "Update within minutes"
        required: false
        default: "15"
jobs:
  twitter:
    runs-on: ubuntu-latest
    steps:
      - uses: azu/rss-to-twitter@v2
        with:
          # RSS feed URL
          RSS_URL: "https://zenn.dev/testkun08080/feed"
          TWEET_TEMPLATE: '"%title%" %url%'
          UPDATE_WITHIN_MINUTES: ${{ inputs.updateMinutes }}
          TWITTER_APIKEY: ${{ secrets.TWITTER_APIKEY }}
          TWITTER_APIKEY_SECRET: ${{ secrets.TWITTER_APIKEY_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
