name: qiita publish articles

on:
  push:
    branches:
      - main
    paths:
      - 'articles/**/*.md' # articles フォルダ以下のすべての .md ファイル
  workflow_dispatch: # 手動トリガーも許可
    
permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish_articles:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run
        uses: C-Naoki/zenn-qiita-sync@main
        with:
          qiita-token: ${{ secrets.QIITA_TOKEN }}
